using System;
using UnityEngine;

namespace Ahmed.Data
{
    /// <summary>Which upgrade track an attack scales with.</summary>
    public enum AttackFamily { Box, Kick }

    /// <summary>
    /// Combat state. Mirrors the browser build's <c>state</c> field one for
    /// one, and the Unreal port's EFighterState, so the three builds can be
    /// compared line by line when one of them misbehaves.
    /// </summary>
    public enum FighterState { Idle, Walk, Attack, Hit, Block, Dash, Down, Dead }

    /// <summary>Traversal and demolition talents, found in the world, never bought.</summary>
    public enum Ability { None, Vault, DashLeap, PowerKick, Haymaker, HawkFist }

    /// <summary>What a sealed route wants from the player.</summary>
    public enum GateType { Stash, Ledge, Gap, Shutter, Wall }

    /// <summary>
    /// How far away an opponent is, in the only terms that matter to choosing
    /// a strike. A kickboxer has an answer at Long; a boxer does not, and that
    /// absence is what makes him close the distance.
    /// </summary>
    public enum RangeBand { Out, Long, Mid, Close }

    /// <summary>
    /// The playfield is a strip: X runs along the stage, Z is depth, Y is up.
    ///
    /// Note the axes. The browser draws in canvas pixels with Y down, and the
    /// Unreal port runs X along with Y as depth and Z up. Unity is Y-up, so
    /// depth is Z here and nowhere else. Every one of these came across from
    /// AhmedGameplay in the Unreal build, converted from centimetres.
    /// </summary>
    public static class Playfield
    {
        public const float DepthMin = -4.20f;
        public const float DepthMax = 4.20f;

        /// <summary>Reserved width so fights never happen under the HUD.</summary>
        public const float ArenaWidth = 22.0f;

        public const float StaminaRegenPerSecond = 24f;
        public const float BlockDamageMultiplier = 0.20f;
        public const float ParryWindow = 0.20f;
        public const float ComboWindow = 0.95f;
        public const float ComboResetTime = 1.7f;
        public const float RageMax = 100f;

        /// <summary>At most this many enemies swing at once, so crowds stay fair.</summary>
        public const int MaxSimultaneousAttackers = 2;

        /// <summary>One canvas pixel in metres. See Tools/export/export.mjs.</summary>
        public const float PixelsToMetres = 0.024f;
    }

    /* ===================================================================
     * The tables.
     *
     * Every one of these is generated by Tools/export/export.mjs from the
     * browser project's assets/*.js, which is the source of truth for every
     * number in the game. Never edit the JSON: edit the assets (the control
     * panel next door is the comfortable way), re-export, press play.
     *
     * The field names have to match the JSON keys exactly, because that is
     * how JsonUtility binds -- and enums cross as strings rather than as the
     * integers JsonUtility would want, so that reordering an enum cannot
     * silently turn every jab into a kick. `Resolve` does the parsing.
     * =================================================================== */

    [Serializable]
    public class AttackRow
    {
        public string name;
        public string family;
        public float damage;
        public float startup;
        public float active;
        public float recovery;
        public float reach;
        public float depthTolerance;
        public float knockback;
        public float staminaCost;
        public bool heavy;
        public bool multiHit;

        [NonSerialized] public AttackFamily Family;

        public float TotalTime { get { return startup + active + recovery; } }

        public void Resolve()
        {
            Family = (AttackFamily)Enum.Parse(typeof(AttackFamily), family, true);
        }
    }

    [Serializable]
    public class FighterRow
    {
        public string name;
        public string displayName;
        public string displayNameArabic;
        public float maxHealth;
        public float powerMultiplier;
        public float moveSpeed;
        public float preferredRange;
        public float attackInterval;
        public float guardChance;
        public bool hitAndRun;
        public bool boss;
        public int experienceValue;
        public string[] moves;
        /// <summary>Name of the row in styles.json, or empty for the player.</summary>
        public string fightStyle;
    }

    [Serializable]
    public class StyleStrike
    {
        public string attackRow;
        public string[] bands;
        public float weight;
        public float opensCombination;

        [NonSerialized] public RangeBand[] Bands;

        public void Resolve()
        {
            Bands = new RangeBand[bands == null ? 0 : bands.Length];
            for (int i = 0; i < Bands.Length; i++)
            {
                Bands[i] = (RangeBand)Enum.Parse(typeof(RangeBand), bands[i], true);
            }
        }

        public bool ThrownFrom(RangeBand band)
        {
            for (int i = 0; i < Bands.Length; i++)
            {
                if (Bands[i] == band) { return true; }
            }
            return false;
        }
    }

    /// <summary>
    /// A fighting style: where a fighter wants to stand, how it gets there,
    /// what it throws from where it is, and what it does after.
    ///
    /// Derived per archetype from the roster by the exporter rather than
    /// authored, so a style cannot drift away from the numbers it came from.
    /// </summary>
    [Serializable]
    public class StyleRow
    {
        public string name;
        public string displayName;

        public float preferredRange;
        public float rangeDiscipline;
        public float resetDistance;

        public float bounceRate;
        public float bounceAmplitude;
        public float circleTendency;
        public float circleSwitchTime;

        public StyleStrike[] strikes;
        public float attackInterval;
        public float rhythmJitter;
        public int maxComboLength;

        public float guardChance;
        public bool guardsWhileAdvancing;
        public float counterChance;

        public void Resolve()
        {
            if (strikes == null) { strikes = new StyleStrike[0]; }
            for (int i = 0; i < strikes.Length; i++) { strikes[i].Resolve(); }
        }

        /// <summary>
        /// Which band a distance falls in, given this style's own reach.
        /// Relative rather than absolute because "close" means something
        /// different to a lanky kickboxer than to a squat grappler, and a
        /// fixed threshold would leave the tall fighter with no mid range.
        /// </summary>
        public RangeBand BandFor(float distance)
        {
            float r = Mathf.Max(0.40f, preferredRange);
            if (distance <= r * 0.55f) { return RangeBand.Close; }
            if (distance <= r * 1.05f) { return RangeBand.Mid; }
            if (distance <= r * 1.85f) { return RangeBand.Long; }
            return RangeBand.Out;
        }

        /// <summary>
        /// Pick a strike legal at this band, weighted across this style plus
        /// anything the fighter has gained since (an enraged boss's finisher).
        ///
        /// Returns null when there is nothing to throw from here, which is a
        /// real answer and not a failure: it is what makes a boxer walk
        /// forward rather than swing at air.
        /// </summary>
        public StyleStrike ChooseStrike(RangeBand band, System.Collections.Generic.List<StyleStrike> extra)
        {
            // Weights are normalised across what is legal *now* rather than
            // authored to sum to one, so removing a strike from a style never
            // means re-tuning every other strike in it.
            float total = 0f;
            for (int i = 0; i < strikes.Length; i++)
            {
                if (Legal(strikes[i], band)) { total += strikes[i].weight; }
            }
            if (extra != null)
            {
                for (int i = 0; i < extra.Count; i++)
                {
                    if (Legal(extra[i], band)) { total += extra[i].weight; }
                }
            }
            if (total <= 0f) { return null; }

            float roll = UnityEngine.Random.Range(0f, total);
            for (int i = 0; i < strikes.Length; i++)
            {
                if (!Legal(strikes[i], band)) { continue; }
                roll -= strikes[i].weight;
                if (roll <= 0f) { return strikes[i]; }
            }
            if (extra != null)
            {
                for (int i = 0; i < extra.Count; i++)
                {
                    if (!Legal(extra[i], band)) { continue; }
                    roll -= extra[i].weight;
                    if (roll <= 0f) { return extra[i]; }
                }
            }
            return null;
        }

        private static bool Legal(StyleStrike s, RangeBand band)
        {
            return s != null && !string.IsNullOrEmpty(s.attackRow)
                && s.weight > 0f && s.ThrownFrom(band);
        }
    }

    [Serializable]
    public class WaveRow
    {
        /// <summary>Distance along the stage that triggers the lock. Negative fires at once.</summary>
        public float triggerDistance;
        public string[] fighters;
        /// <summary>-1 uses the stage's own tier.</summary>
        public int tierOverride;
    }

    [Serializable]
    public class GateRow
    {
        public float distance;
        public string type;
        public string rewardAbility;
        public int rewardExperience;

        [NonSerialized] public GateType Type;
        [NonSerialized] public Ability RewardAbility;

        public void Resolve()
        {
            Type = (GateType)Enum.Parse(typeof(GateType), type, true);
            RewardAbility = (Ability)Enum.Parse(typeof(Ability), rewardAbility, true);
        }
    }

    [Serializable]
    public class StageRow
    {
        public string name;
        public int index;
        public string displayName;
        public string displayNameArabic;
        public string theme;
        public string briefing;
        public string briefingArabic;
        public string hint;
        public float length;
        public int tier;
        public bool bossStage;
        public bool survival;
        public WaveRow[] waves;
        public GateRow[] gates;

        public void Resolve()
        {
            if (gates == null) { gates = new GateRow[0]; }
            if (waves == null) { waves = new WaveRow[0]; }
            for (int i = 0; i < gates.Length; i++) { gates[i].Resolve(); }
        }
    }

    [Serializable]
    public class PlayerRow
    {
        public string displayName;
        public string displayNameArabic;
        public float baseHealth;
        public float baseStamina;
        public float baseMana;
        public float basePower;
        public float baseMoveSpeed;
        public float baseReach;
        public float healthPerVitality;
        public float staminaPerStamina;
        public float speedPerSpeed;
        public float manaRegenPerSecond;
        public float manaPerLandedHit;
        public int upgradeMaxLevel;
    }

    [Serializable]
    public class LevelRow
    {
        public int level;
        public int experienceToNext;
        public string title;
    }

    [Serializable]
    public class TalentRow
    {
        public string name;
        public string ability;
        public string displayName;
        public string displayNameArabic;
        public string icon;
        public float manaCost;
        public string description;

        [NonSerialized] public Ability Ability;

        public void Resolve()
        {
            Ability = (Ability)Enum.Parse(typeof(Ability), ability, true);
        }
    }

    /// <summary>The result of one landed blow, handed back to whoever threw it.</summary>
    public struct HitResult
    {
        public float damage;
        public bool blocked;
        public bool parried;
        public bool knockdown;
        public bool killed;
        public Vector3 impactPoint;
    }
}
