#pragma once

/**
 * GENERATED by Tools/blender/measure_stances.py from each set's guard clip
 * (Content/Animation, A_<Set>_Guard, frame 0) -- never hand-edit; run the tool
 * again when a guard changes (--check says when).
 *
 * Each man's designed stance, measured the way SaudIK::MeasurePosture measures
 * a pose: the line of his hips and of his shoulders against level (degrees, +
 * his right side high), his trunk (spine_01 to spine_03) tipped toward his right,
 * his head joint off his spine's line toward his right (cm), his eyes' line
 * against level, and his hips' yaw less his feet's (degrees). The runtime
 * straightens only what departs from these. The joints are the guard's own,
 * mesh frame (cm, X forward, Y his right, Z up), for the harness.
 */

#if defined(SAUD_HARNESS)
	#include "HarnessTypes.h"
#else
	#include "CoreMinimal.h"
#endif

namespace SaudStances
{
	/** A pose's joints, mesh frame, and the head's left-to-right axis. */
	struct FJoints
	{
		FVector Pelvis, Hip[2], Knee[2], Ankle[2], Ball[2], Spine[3], Neck, Head, Shoulder[2];
		FVector HeadSide;
	};

	struct FStance
	{
		const char* Set;          // the motion set, A_<Set>_*
		const char* Guard;        // build_saud.GUARDS' name
		float HipRoll;            // degrees, + right high
		float ShoulderRoll;       // degrees, + right high
		float TrunkTilt;          // degrees toward his right
		float HeadOff;            // cm toward his right
		float EyeRoll;            // degrees, + right high
		float Twist;              // degrees, hips' yaw less feet's
		FJoints Joints;           // frame 0 of his guard
	};

	constexpr int NumStances = 5;

	inline const FStance Stances[NumStances] = {
		{ "Saud", "mma", 0.000f, -1.035f, -3.400f, 0.257f, 0.157f, -26.053f,
		  { FVector(0.000, 0.000, 88.095), FVector(3.155, -8.642, 88.095), FVector(-3.155, 8.642, 88.095), FVector(25.169, -9.730, 50.108), FVector(-2.798, 27.288, 48.333), FVector(15.489, -13.248, 7.000), FVector(-23.214, 19.932, 9.689), FVector(31.030, -11.883, 2.433), FVector(-10.959, 28.514, 3.333), FVector(-0.000, 0.000, 103.695), FVector(2.169, 0.000, 119.143), FVector(5.830, -0.000, 136.358), FVector(8.302, -0.000, 143.966), FVector(12.255, -0.000, 158.710), FVector(15.740, -17.105, 139.778), FVector(2.533, 19.724, 139.071), FVector(-0.001, 1.000, 0.003) } },
		{ "Street", "boxer", -0.000f, 1.219f, -1.973f, -0.322f, -0.405f, -11.501f,
		  { FVector(0.000, -0.000, 92.688), FVector(3.919, -8.324, 92.688), FVector(-3.919, 8.324, 92.688), FVector(14.104, -13.860, 50.328), FVector(4.534, 14.007, 49.968), FVector(20.518, -19.332, 6.817), FVector(-10.482, 19.326, 8.610), FVector(36.117, -18.033, 2.430), FVector(1.226, 28.758, 2.430), FVector(0.000, -0.000, 108.288), FVector(0.934, -0.000, 123.860), FVector(2.686, 0.000, 141.373), FVector(3.085, -0.000, 149.363), FVector(4.604, -0.000, 164.552), FVector(11.746, -17.839, 141.120), FVector(-5.270, 18.351, 141.971), FVector(0.002, 1.000, -0.007) } },
		{ "Boss", "peekaboo", -0.000f, 4.886f, -4.401f, 0.124f, -0.215f, -11.761f,
		  { FVector(0.000, 0.000, 88.406), FVector(3.919, -8.324, 88.406), FVector(-3.919, 8.324, 88.406), FVector(24.162, -12.071, 49.612), FVector(3.482, 23.484, 47.857), FVector(16.990, -21.093, 6.817), FVector(-16.994, 21.084, 8.624), FVector(32.588, -19.794, 2.430), FVector(-4.931, 30.049, 2.430), FVector(0.000, 0.000, 104.006), FVector(2.184, -0.000, 119.452), FVector(6.077, -0.000, 136.617), FVector(7.677, -0.000, 144.455), FVector(10.434, -0.000, 159.468), FVector(14.996, -17.839, 135.001), FVector(-1.698, 18.351, 138.407), FVector(-0.000, 1.000, -0.004) } },
		{ "Saqr", "kickboxer", -0.000f, 0.975f, -1.233f, -0.515f, -0.210f, -13.146f,
		  { FVector(0.000, 0.000, 93.535), FVector(3.919, -8.324, 93.535), FVector(-3.919, 8.324, 93.535), FVector(13.297, -13.117, 50.898), FVector(0.324, 18.636, 51.056), FVector(19.496, -18.287, 7.319), FVector(-12.472, 18.280, 8.624), FVector(34.978, -17.472, 2.430), FVector(-0.410, 27.245, 2.430), FVector(0.000, 0.000, 109.135), FVector(0.623, -0.000, 124.722), FVector(1.678, -0.000, 142.291), FVector(1.997, -0.000, 150.284), FVector(3.816, -0.000, 165.440), FVector(10.740, -17.839, 142.128), FVector(-6.284, 18.351, 142.809), FVector(0.002, 1.000, -0.004) } },
		{ "Zayos", "heavy", 0.000f, 1.816f, -0.857f, 0.063f, -0.182f, -14.240f,
		  { FVector(0.000, 0.000, 91.700), FVector(1.828, -9.017, 91.700), FVector(-1.828, 9.017, 91.700), FVector(13.335, -17.636, 50.202), FVector(-0.814, 21.094, 49.487), FVector(13.958, -27.429, 6.981), FVector(-13.929, 27.429, 7.628), FVector(29.563, -27.429, 2.430), FVector(-0.120, 34.252, 2.430), FVector(0.000, 0.000, 107.300), FVector(0.779, 0.000, 122.881), FVector(2.530, 0.000, 140.393), FVector(3.807, -0.000, 148.291), FVector(5.923, -0.000, 163.408), FVector(7.065, -19.482, 139.863), FVector(-0.780, 19.721, 141.131), FVector(0.000, 1.000, -0.003) } },
	};

	/** The stance of a motion set by name, or null (the Island's creatures have none). */
	inline const FStance* Find(const char* Set)
	{
		if (!Set) return nullptr;
		for (const FStance& S : Stances)
		{
			const char* A = S.Set;
			const char* B = Set;
			while (*A && *A == *B) { ++A; ++B; }
			if (*A == 0 && *B == 0) return &S;
		}
		return nullptr;
	}
}
