using Ahmed.Data;

public static class TestData
{
    public static WorldArea[] Areas = new WorldArea[] {
        new WorldArea{index=0,name="SOUQ",mapX=300,mapY=250,startArea=0,west=new WorldLink{to=7,requiredAbility="Vault",afterCleared=7,distance=-1.000000f},east=new WorldLink{to=1,requiredAbility="None",afterCleared=-1,distance=-1.000000f},door=new WorldLink{to=8,requiredAbility="HawkFist",afterCleared=-1,distance=45.600000f}},
        new WorldArea{index=1,name="GYM",mapX=470,mapY=250,startArea=0,west=new WorldLink{to=0,requiredAbility="None",afterCleared=-1,distance=-1.000000f},east=new WorldLink{to=2,requiredAbility="None",afterCleared=-1,distance=-1.000000f},door=new WorldLink{to=-1,requiredAbility="None",afterCleared=-1,distance=-1.000000f}},
        new WorldArea{index=2,name="SHARQ",mapX=640,mapY=250,startArea=0,west=new WorldLink{to=1,requiredAbility="None",afterCleared=-1,distance=-1.000000f},east=new WorldLink{to=3,requiredAbility="None",afterCleared=-1,distance=-1.000000f},door=new WorldLink{to=-1,requiredAbility="None",afterCleared=-1,distance=-1.000000f}},
        new WorldArea{index=3,name="TOWERS",mapX=810,mapY=250,startArea=0,west=new WorldLink{to=2,requiredAbility="None",afterCleared=-1,distance=-1.000000f},east=new WorldLink{to=4,requiredAbility="DashLeap",afterCleared=-1,distance=-1.000000f},door=new WorldLink{to=-1,requiredAbility="None",afterCleared=-1,distance=-1.000000f}},
        new WorldArea{index=4,name="MARINA",mapX=980,mapY=250,startArea=0,west=new WorldLink{to=3,requiredAbility="DashLeap",afterCleared=-1,distance=-1.000000f},east=new WorldLink{to=5,requiredAbility="None",afterCleared=-1,distance=-1.000000f},door=new WorldLink{to=-1,requiredAbility="None",afterCleared=-1,distance=-1.000000f}},
        new WorldArea{index=5,name="FAILAKA",mapX=980,mapY=410,startArea=0,west=new WorldLink{to=4,requiredAbility="None",afterCleared=-1,distance=-1.000000f},east=new WorldLink{to=6,requiredAbility="PowerKick",afterCleared=-1,distance=-1.000000f},door=new WorldLink{to=-1,requiredAbility="None",afterCleared=-1,distance=-1.000000f}},
        new WorldArea{index=6,name="JAHRA",mapX=810,mapY=410,startArea=0,west=new WorldLink{to=5,requiredAbility="PowerKick",afterCleared=-1,distance=-1.000000f},east=new WorldLink{to=7,requiredAbility="Haymaker",afterCleared=-1,distance=-1.000000f},door=new WorldLink{to=-1,requiredAbility="None",afterCleared=-1,distance=-1.000000f}},
        new WorldArea{index=7,name="DESERT",mapX=470,mapY=410,startArea=0,west=new WorldLink{to=6,requiredAbility="Haymaker",afterCleared=-1,distance=-1.000000f},east=new WorldLink{to=0,requiredAbility="Vault",afterCleared=7,distance=-1.000000f},door=new WorldLink{to=-1,requiredAbility="None",afterCleared=-1,distance=-1.000000f}},
        new WorldArea{index=8,name="ARENA",mapX=130,mapY=250,startArea=0,west=new WorldLink{to=0,requiredAbility="HawkFist",afterCleared=-1,distance=-1.000000f},east=new WorldLink{to=-1,requiredAbility="None",afterCleared=-1,distance=-1.000000f},door=new WorldLink{to=-1,requiredAbility="None",afterCleared=-1,distance=-1.000000f}},
    };

    public static StageRow[] Stages = new StageRow[] {
        new StageRow{name="SouqMubarakiya",index=0,displayName="SOUQ MUBARAKIYA",length=72.000000f,tier=0,bossStage=false,survival=false,waves=new WaveRow[]{new WaveRow{triggerDistance=7.200000f,tierOverride=-1,fighters=new string[]{"Thug","Thug"}},new WaveRow{triggerDistance=30.000000f,tierOverride=-1,fighters=new string[]{"Thug","Thug","Brawler"}},new WaveRow{triggerDistance=56.400000f,tierOverride=-1,fighters=new string[]{"Brawler","Brawler","Thug"}}},gates=new GateRow[]{new GateRow{distance=27.600000f,type="Wall",rewardAbility="None",rewardExperience=450}}},
        new StageRow{name="SalmiyaGym",index=1,displayName="SALMIYA GYM",length=62.400000f,tier=0,bossStage=false,survival=false,waves=new WaveRow[]{new WaveRow{triggerDistance=6.720000f,tierOverride=-1,fighters=new string[]{"Thug"}},new WaveRow{triggerDistance=16.320000f,tierOverride=-1,fighters=new string[]{"Brawler"}},new WaveRow{triggerDistance=25.920000f,tierOverride=-1,fighters=new string[]{"Kicker","Thug"}},new WaveRow{triggerDistance=35.520000f,tierOverride=-1,fighters=new string[]{"Brawler","Brawler"}},new WaveRow{triggerDistance=45.120000f,tierOverride=-1,fighters=new string[]{"Kicker","Kicker"}},new WaveRow{triggerDistance=54.000000f,tierOverride=-1,fighters=new string[]{"Kicker","Brawler","Brawler"}}},gates=new GateRow[]{new GateRow{distance=48.000000f,type="Stash",rewardAbility="Vault",rewardExperience=0}}},
        new StageRow{name="SharqFishMarket",index=2,displayName="SHARQ FISH MARKET",length=86.400000f,tier=1,bossStage=false,survival=false,waves=new WaveRow[]{new WaveRow{triggerDistance=16.800000f,tierOverride=-1,fighters=new string[]{"Runner","Runner","Thug"}},new WaveRow{triggerDistance=48.000000f,tierOverride=-1,fighters=new string[]{"Runner","Runner","Brawler","Brawler"}},new WaveRow{triggerDistance=78.000000f,tierOverride=-1,fighters=new string[]{"Bouncer","Runner","Runner"}}},gates=new GateRow[]{new GateRow{distance=25.200000f,type="Ledge",rewardAbility="DashLeap",rewardExperience=0}}},
        new StageRow{name="KuwaitTowers",index=3,displayName="KUWAIT TOWERS",length=67.200000f,tier=1,bossStage=false,survival=false,waves=new WaveRow[]{new WaveRow{triggerDistance=19.200000f,tierOverride=-1,fighters=new string[]{"Kicker","Kicker","Brawler","Brawler","Thug"}},new WaveRow{triggerDistance=52.800000f,tierOverride=-1,fighters=new string[]{"Grappler","Kicker","Kicker","Brawler"}}},gates=new GateRow[]{new GateRow{distance=38.400000f,type="Wall",rewardAbility="None",rewardExperience=500}}},
        new StageRow{name="MarinaCrescent",index=4,displayName="MARINA CRESCENT",length=52.800000f,tier=2,bossStage=true,survival=false,waves=new WaveRow[]{new WaveRow{triggerDistance=10.800000f,tierOverride=-1,fighters=new string[]{"Capo","Runner","Runner"}},new WaveRow{triggerDistance=27.600000f,tierOverride=-1,fighters=new string[]{"Bouncer","Capo"}},new WaveRow{triggerDistance=45.600000f,tierOverride=-1,fighters=new string[]{"Saqr"}}},gates=new GateRow[]{new GateRow{distance=22.800000f,type="Gap",rewardAbility="PowerKick",rewardExperience=0}}},
        new StageRow{name="FailakaIsland",index=5,displayName="FAILAKA ISLAND",length=60.000000f,tier=2,bossStage=false,survival=false,waves=new WaveRow[]{new WaveRow{triggerDistance=12.000000f,tierOverride=-1,fighters=new string[]{"Grappler","Brawler"}},new WaveRow{triggerDistance=28.800000f,tierOverride=-1,fighters=new string[]{"Grappler","Grappler","Kicker"}},new WaveRow{triggerDistance=44.400000f,tierOverride=-1,fighters=new string[]{"Grappler","Grappler","Capo"}}},gates=new GateRow[]{new GateRow{distance=51.600000f,type="Shutter",rewardAbility="None",rewardExperience=600}}},
        new StageRow{name="JahraRoad",index=6,displayName="JAHRA ROAD",length=81.600000f,tier=3,bossStage=false,survival=false,waves=new WaveRow[]{new WaveRow{triggerDistance=14.400000f,tierOverride=-1,fighters=new string[]{"Runner","Runner"}},new WaveRow{triggerDistance=30.000000f,tierOverride=-1,fighters=new string[]{"Bouncer","Runner"}},new WaveRow{triggerDistance=45.600000f,tierOverride=-1,fighters=new string[]{"Capo","Kicker"}},new WaveRow{triggerDistance=60.000000f,tierOverride=-1,fighters=new string[]{"Bouncer","Kicker"}},new WaveRow{triggerDistance=73.200000f,tierOverride=-1,fighters=new string[]{"Bouncer","Capo"}}},gates=new GateRow[]{new GateRow{distance=26.400000f,type="Shutter",rewardAbility="Haymaker",rewardExperience=0}}},
        new StageRow{name="DesertCamp",index=7,displayName="DESERT CAMP",length=72.000000f,tier=3,bossStage=false,survival=false,waves=new WaveRow[]{new WaveRow{triggerDistance=21.600000f,tierOverride=-1,fighters=new string[]{"Kicker","Kicker","Brawler","Brawler","Capo"}},new WaveRow{triggerDistance=55.200000f,tierOverride=-1,fighters=new string[]{"Champ","Champ","Grappler"}}},gates=new GateRow[]{new GateRow{distance=27.600000f,type="Wall",rewardAbility="HawkFist",rewardExperience=250}}},
        new StageRow{name="KuwaitArena",index=8,displayName="KUWAIT ARENA",length=38.400000f,tier=4,bossStage=true,survival=false,waves=new WaveRow[]{new WaveRow{triggerDistance=10.080000f,tierOverride=-1,fighters=new string[]{"Champ","Champ"}},new WaveRow{triggerDistance=21.600000f,tierOverride=-1,fighters=new string[]{"Boss"}}},gates=new GateRow[]{}},
        new StageRow{name="Survival",index=9,displayName="SURVIVAL",length=33.600000f,tier=0,bossStage=false,survival=true,waves=new WaveRow[]{new WaveRow{triggerDistance=-1.000000f,tierOverride=0,fighters=new string[]{"Thug","Thug"}}},gates=new GateRow[]{}},
    };
}
